### ISSUE TITLE
Content updates

### ISSUE THREAD

**Issue by MaisaMilena** [sunshine-cybernetics/SunshineWeb#1]
Updates asked by John.

1. Under Projects:
- [x] should have link to our Telegram
- [x] change Formality: description to: "An efficient dependently-typed systems programming language and proof assistant. "
- [x] change Moonad description to : "A Peer to Peer Operating System"

2. Under "Our Advisors"
- [x] change Aaron Stomp's job description to "Professor of Computer Science"
- [x] change Aaron Stump's advisor description to "Type Theory, Agda, Cedille", with Cedille linking to cedille.github.io
- [x] change Jacob Arluck's advisor description to "Smart contracts, platform governance, consensus"

3. Under "Meet our team"
- [x] maybe get rid of "The superheros"
- [x] Leonardo is no longer on the team
- [x] Phoebe's job description should be "Operations"
- [x] Should we have short team bios when you click/mouseover on people's photos?

4. Under "Sponsors"
- [x] remove "Who support us" and "Sponsors", should just say "Supported by:"

5. Contact
- [x] Under "We work remotely", should be " Currently in the USA and Brazil"

**Comment by MaisaMilena** [comment]
@johnchandlerburnham about the team bios, I just paused it until getting the website online, now we can work on this. What are your thoughts about the bio? I thought about something related to "what I do on the company/hobbies" to make it more fun

**Comment by johnchandlerburnham** [comment]
@MaisaMilena Actually, I had an idea. What if we just had the team pictures just link to our github profiles when you click on them? I think that's a simple way to communicate "what I do" without having to add blobs of text to the site
